feat(init): first commit
camptocamp/terraform-azure-flexible-server pull request #1
Opened 2022-09-27 12:27 UTC by jbarascut

2022-09-27 14:25 UTC, fsismondi requested changes

2022-09-27 14:25 UTC, fsismondi commented on variables.tf
> +  description = ""
should be described

2022-09-27 14:25 UTC, fsismondi commented on main.tf
> +resource "azurerm_management_lock" "this" {
good you added this

2022-09-27 14:25 UTC, fsismondi commented on main.tf
> +resource "azurerm_management_lock" "this" {
will it work tho? when you actually need to delete a DB cluster , how do u do this?

2022-10-06 08:33 UTC, fsismondi requested changes

2022-10-06 08:33 UTC, fsismondi commented on variables.tf
> +  default     = 35
is this default in camptocamp? how are most of our psql servers configured?

2022-10-06 08:33 UTC, fsismondi commented on variables.tf
> +  description = "Cron maintenance window (default sunday midnight)."
0,0,0 is sunday midnight in CET ? or local time?

2022-10-06 08:33 UTC, fsismondi commented on variables.tf
> +  description = ""
"The ID of the private DNS zone to create the PostgreSQL Flexible Server. Changing this forces a new PostgreSQL Flexible Server to be created."

2022-10-06 13:34 UTC, jbarascut commented on variables.tf
> +  default     = 35
Possible range between 7 to 35. 35 is camptocamp default

2022-10-06 13:35 UTC, jbarascut commented on variables.tf
> +  description = "Cron maintenance window (default sunday midnight)."
Server time maybe

2022-10-10 08:40 UTC, fsismondi approved these changes

2022-10-10 09:35 UTC, fsismondi commented on variables.tf
> +  description = "Name for the PostgreSQL Flexible Server."
```suggestion
  description = "Name for the PostgreSQL Flexible Server. This is also used for the DNS private zone name."
```

2022-10-10 09:41 UTC, merged